# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TourII.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TourII(object):
    def setupUi(self, TourII):
        TourII.setObjectName("TourII")
        TourII.setWindowModality(QtCore.Qt.ApplicationModal)
        TourII.resize(959, 583)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Ico/logo_301.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TourII.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(TourII)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(TourII)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.frame = QtWidgets.QFrame(TourII)
        self.frame.setMinimumSize(QtCore.QSize(0, 41))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 41))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(75, 28))
        self.pushButton.setMaximumSize(QtCore.QSize(75, 28))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.cancel_btn = QtWidgets.QPushButton(self.frame)
        self.cancel_btn.setMinimumSize(QtCore.QSize(75, 28))
        self.cancel_btn.setMaximumSize(QtCore.QSize(75, 28))
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(TourII)
        self.cancel_btn.clicked.connect(TourII.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TourII)
        TourII.setTabOrder(self.pushButton, self.cancel_btn)
        TourII.setTabOrder(self.cancel_btn, self.tableView)

    def retranslateUi(self, TourII):
        _translate = QtCore.QCoreApplication.translate
        TourII.setWindowTitle(_translate("TourII", "F-4C ФАС России II тур"))
        self.pushButton.setText(_translate("TourII", "Печать"))
        self.cancel_btn.setText(_translate("TourII", "Отмена"))
import Resourses_rc
