# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TourIII.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TourIII(object):
    def setupUi(self, TourIII):
        TourIII.setObjectName("TourIII")
        TourIII.setWindowModality(QtCore.Qt.ApplicationModal)
        TourIII.resize(930, 449)
        self.tableWidget = QtWidgets.QTableWidget(TourIII)
        self.tableWidget.setGeometry(QtCore.QRect(20, 60, 891, 311))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(11)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget.verticalHeader().setVisible(False)
        self.pushButton = QtWidgets.QPushButton(TourIII)
        self.pushButton.setGeometry(QtCore.QRect(60, 400, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(TourIII)
        QtCore.QMetaObject.connectSlotsByName(TourIII)

    def retranslateUi(self, TourIII):
        _translate = QtCore.QCoreApplication.translate
        TourIII.setWindowTitle(_translate("TourIII", "F-4C ФАС России"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TourIII", "№"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TourIII", "Фамилия"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TourIII", "Имя"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TourIII", "Регион"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("TourIII", "Прототип"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("TourIII", "Стенд общ."))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("TourIII", "I тур"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("TourIII", "II тур"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("TourIII", "III тур"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("TourIII", "Результат"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("TourIII", "Место"))
        self.pushButton.setText(_translate("TourIII", "Печать"))
